name: qcarchive-user-submit
channels:
  - conda-forge
  - openeye
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - ambertools=24.8=cuda_None_nompi_py311h523f5e4_101
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.12.1=pyhcf101f3_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - apsw=3.51.2.0=py311hc949640_0
  - argcomplete=3.6.3=pyhd8ed1ab_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py311h9408147_2
  - arpack=3.9.1=nompi_h1f29f7c_102
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.1.0=pyhcf101f3_0
  - attrs=25.4.0=pyhcf101f3_1
  - babel=2.18.0=pyhcf101f3_0
  - backports.zstd=1.3.0=py311hee243d0_0
  - basis_set_exchange=0.11=pyhd8ed1ab_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - bleach=6.3.0=pyhcf101f3_1
  - bleach-with-css=6.3.0=hbca2aae_1
  - blosc=1.21.6=h7dd00d9_1
  - brotli=1.2.0=h7d5ae5b_1
  - brotli-bin=1.2.0=hc919400_1
  - brotli-python=1.2.0=py311hdc60ec4_1
  - bson=0.5.10=pyhd8ed1ab_0
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.6=hc919400_0
  - c-blosc2=2.23.0=hf9886e1_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=7.0.1=pyhd8ed1ab_0
  - cairo=1.18.4=h6a3b0d2_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py311hd10dc20_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - click-option-group=0.5.6=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311h7d85929_4
  - cpython=3.11.14=py311hd8ed1ab_3
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - debugpy=1.8.20=py311h8948835_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fftw=3.3.10=nompi_hea23c72_111
  - filelock=3.24.2=pyhd8ed1ab_0
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py311ha9b3269_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=hce30654_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - fsspec=2026.2.0=pyhd8ed1ab_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py311hd340a2e_2
  - greenlet=3.3.1=py311h8948835_1
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - hdf4=4.2.15=h2ee6834_7
  - hdf5=1.14.6=nompi_had3affe_106
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - ipykernel=7.2.0=pyh5552912_1
  - ipython=9.10.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - json5=0.13.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.26.0=hcf101f3_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyhe01879c_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.4=pyhcf101f3_0
  - jupyterlab=4.5.4=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - khronos-opencl-icd-loader=2024.10.24=h5505292_1
  - kiwisolver=1.4.9=py311h26d6576_2
  - krb5=1.21.3=h237132a_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.18=hdfa7624_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libaec=1.1.5=h8664d51_0
  - libblas=3.11.0=5_h51639a9_openblas
  - libboost=1.86.0=hf493ff8_4
  - libboost-python=1.86.0=py311h08cb3c8_5
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libcurl=8.18.0=he38603e_0
  - libcxx=21.1.8=h55c6f16_2
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.4=hf6b4638_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_17
  - libgfortran=15.2.0=h07b0088_17
  - libgfortran5=15.2.0=hdae7583_17
  - libglib=2.86.3=he378b5c_1
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=5_hd9741b5_openblas
  - liblzma=5.8.2=h8088a28_0
  - libnetcdf=4.9.2=nompi_h2d3d5cf_118
  - libnghttp2=1.67.0=hc438710_0
  - libntlm=1.8=h5505292_0
  - libopenblas=0.3.30=openmp_ha158390_4
  - libpng=1.6.55=h132b30e_0
  - libpq=18.1=h944245b_2
  - libprotobuf=6.31.1=h98f38fd_4
  - librdkit=2025.09.5=h26160e4_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.51.1=h1b79a29_1
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.7.1=h4030677_1
  - libtorch=2.8.0=cpu_generic_h0fc8bc6_2
  - libuv=1.51.0=h6caf38d_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.9=h4a9ca0c_0
  - libzip=1.11.2=h1336266_0
  - libzlib=1.3.1=h8359307_2
  - lightning-utilities=0.15.2=pyhd8ed1ab_0
  - llvm-openmp=21.1.8=h4a912ad_0
  - lz4-c=1.10.0=h286801f_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py311ha9b3269_0
  - matplotlib-base=3.10.8=py311h29553df_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mda-xdrlib=0.2.0=pyhd8ed1ab_1
  - mdtraj=1.11.1=np2py311hd20dc7c_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.2.0=pyhcf101f3_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.2=py311h5a5e7c7_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert-core=7.17.0=pyhcf101f3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf-fortran=4.6.2=nompi_h170865b_101
  - networkx=3.6.1=pyhcf101f3_0
  - nomkl=1.0=h5ca1d4c_0
  - notebook=7.5.3=pyhcf101f3_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numexpr=2.14.1=py311h5890ad2_1
  - numpy=2.4.2=py311had1e860_1
  - ocl_icd_wrapper_apple=1.0.0=h27ca646_0
  - opencl-headers=2025.06.13=h286801f_0
  - openeye-toolkits=2025.2.1=py311_0
  - openff-amber-ff-ports=2025.09.0=pyhd8ed1ab_0
  - openff-forcefields=2026.01.0=pyhd8ed1ab_0
  - openff-interchange=0.5.0=pyhd8ed1ab_0
  - openff-interchange-base=0.5.0=pyhd8ed1ab_0
  - openff-nagl=0.5.4=pyhd8ed1ab_1
  - openff-nagl-base=0.5.4=pyhd8ed1ab_1
  - openff-nagl-models=2025.9.0=pyhd8ed1ab_0
  - openff-qcsubmit=0.57.0=pyhd8ed1ab_1
  - openff-toolkit=0.18.0=pyhd8ed1ab_2
  - openff-toolkit-base=0.18.0=pyhd8ed1ab_2
  - openff-units=0.3.2=pyhd8ed1ab_0
  - openff-utilities=0.1.16=pyhd8ed1ab_1
  - openjpeg=2.5.4=hbfb3c88_0
  - openldap=2.6.10=hbe55e7a_0
  - openmm=8.4.0=py311h12f2354_2_khronos
  - openssl=3.6.1=hd24854e_1
  - optree=0.18.0=py311h5a5e7c7_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=2.3.3=py311hdb8e4fa_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parmed=4.3.1=py311h7193249_0
  - parso=0.8.6=pyhcf101f3_0
  - pcre2=10.47=h30297fc_0
  - perl=5.32.1=7_h4614cfb_perl5
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.1.1=py311hd37aea2_0
  - pint=0.25.2=pyhcf101f3_0
  - pip=26.0.1=pyh8b19718_0
  - pixman=0.46.4=h81086ad_1
  - platformdirs=4.9.2=pyhcf101f3_0
  - pluggy=1.6.0=pyhf9edf01_1
  - prometheus_client=0.24.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.2=py311he363849_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pybind11=2.13.6=pyhff21bea_3
  - pybind11-abi=4=hd8ed1ab_3
  - pybind11-global=2.13.6=pyh217bc35_3
  - pycairo=1.29.0=py311ha1fe154_1
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.10=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py311hf245fc6_0
  - pyedr=0.8.0=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjwt=2.11.0=pyhd8ed1ab_0
  - pyobjc-core=12.1=py311hce6e4fa_0
  - pyobjc-framework-cocoa=12.1=py311h9049b8e_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytables=3.10.2=py311h9aa646e_11
  - pytest=9.0.2=pyhcf101f3_0
  - python=3.11.14=h18782d2_2_cpython
  - python-constraint=1.4.0=pyhff2d567_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytorch=2.8.0=cpu_generic_py311_hf0c13c8_2
  - pytorch-lightning=2.6.1=pyhcf101f3_0
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py311hc290fe0_1
  - pyzmq=27.1.0=py311h13abfa4_0
  - qcelemental=0.29.0=pyhd8ed1ab_1
  - qcportal=0.63=pyhd8ed1ab_0
  - qhull=2020.2=h420ef59_5
  - rdkit=2025.09.5=py311h756a433_0
  - readline=8.3=h46df422_0
  - referencing=0.37.0=pyhcf101f3_0
  - regex=2026.1.15=py311hc949640_0
  - reportlab=4.4.10=pyhcf101f3_1
  - requests=2.32.5=pyhcf101f3_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rich=14.3.2=pyhcf101f3_0
  - rlpycairo=0.4.0=pyh6c17108_0
  - rpds-py=0.30.0=py311h71babbd_0
  - scipy=1.17.0=py311he9931d0_1
  - send2trash=2.1.0=pyh5552912_1
  - setuptools=82.0.0=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=hb028509_0
  - snappy=1.2.2=hada39a4_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8.3=pyhd8ed1ab_0
  - sqlalchemy=2.0.46=py311he363849_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=pyh2585a3b_105
  - tabulate=0.9.0=pyhcf101f3_3
  - terminado=0.18.1=pyhc90fa1f_1
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h892fb3f_3
  - tomli=2.4.0=pyhcf101f3_0
  - torchmetrics=1.8.2=pyhd8ed1ab_0
  - tornado=6.5.4=py311h9408147_0
  - tqdm=4.67.3=pyh8f84b5b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025c=hc9c84f9_1
  - unicodedata2=17.0.1=py311hc949640_0
  - unidecode=1.4.0=pyhcf101f3_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wcwidth=0.6.0=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - xmltodict=1.0.3=pyhcf101f3_0
  - xorg-libice=1.1.2=h5505292_0
  - xorg-libsm=1.2.6=h5505292_0
  - xorg-libx11=1.8.13=hf948f5a_0
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - xorg-libxext=1.3.7=h84a0fba_0
  - xorg-libxt=1.3.1=h5505292_0
  - yaml=0.2.5=h925e9cb_3
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h8359307_2
  - zlib-ng=2.3.3=hed4e4f5_1
  - zstandard=0.25.0=py311h5bb9006_1
  - zstd=1.5.7=hbf9d68e_6

prefix: "/Users/mattthompson/mamba/envs/qcarchive-user-submit"
