---
# deployment of qcarchive prod environments

name: Deployment - QCArchive Prod Environments

on:
  push:
    branches:
      - master
    paths:
      - 'devtools/prod-envs/**.yaml'
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  deploy-conda-env:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env-name:
          - qcarchive-user-submit
          - qcarchive-worker-openff-ani
          - qcarchive-worker-openff-openmm
          - qcarchive-worker-openff-psi4
          - qcarchive-worker-openff-xtb
    steps:
      - name: Checkout code
        uses: nschloe/action-cached-lfs-checkout@v1

      - name: ensure we only have one instance running
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_DANGERBOT_TOKEN_LIMITED }}
        with:
          abort-after-seconds: 60

      - name: Additional info about the build
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Install environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: devtools/prod-envs/${{ matrix.env-name }}.yaml

      - name: Environment Information
        run: |
          conda info
          conda list

      - name: Deploy conda env
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
            mamba install -y anaconda-client
            anaconda -t ${ANACONDA_TOKEN} upload --user openforcefield devtools/prod-envs/${{ matrix.env-name }}.yaml
